In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

NUMPY ARRAY

numpy bir hesaplama kütüphanesidir. Veri dizisidir.

In [4]:
my_list = [10,20,30,40]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list) #listeyi numpy'a çevirdik.

array([10, 20, 30, 40])

In [7]:
my_numpy_array = np.array(my_list) #listeyi bir değişkene atadık.

In [8]:
type(my_numpy_array) #değişken türü array.

numpy.ndarray

In [9]:
my_numpy_array 

array([10, 20, 30, 40])

In [10]:
my_numpy_array[0] #index mantığı çalışır. Kullanılır.

10

In [11]:
my_numpy_array[-1]

40

In [12]:
my_numpy_array[0] = 100 # sıfırıncı elemanını 100 yaptık.

In [13]:
my_numpy_array

array([100,  20,  30,  40])

In [14]:
my_numpy_array.max()

100

In [15]:
my_numpy_array.min()

20

In [16]:
my_numpy_array.mean() #ortalama alır.

47.5

In [17]:
matrix_list = [[1,0,0],[0,1,0],[0,0,1],[0,0,0]]

In [18]:
type(matrix_list)

list

In [19]:
matrix_list[0]

[1, 0, 0]

In [20]:
matrix_list[0][0]

1

In [22]:
numpy_matrix_list = np.array(matrix_list) # matrix şeklinde görünüm

In [23]:
numpy_matrix_list

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [24]:
numpy_matrix_list[0] #liste içindeki ilk elemanı getirir

array([1, 0, 0])

In [25]:
numpy_matrix_list.shape  #4 satır 3 sütun var der.

(4, 3)

arange, numpy için range 'tir. range ile aynı förevi görür.

In [26]:
np.arange(0,10) # 0'dan 10'a kadar git

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0, 30, 2) # 0'dan 30'a ikişer ikişer git.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [28]:
np.zeros(10) #10 tane sıfırdan oluşan liste

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((10, 10)) #shape yaptığımız için bunlar tuple ile oluştururuz.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.ones((10,10)) # 10'a 10 olan 1'li matris.

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

linspace

In [32]:
np.linspace(0,10,10) # 0'dan 10'a kadar eşit artışlarla bir 10'luk düzen oluştur. 

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [33]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

random

In [34]:
np.random.randint(1,10,3) #randint random int demektir. 1'den 10'a kadar 3 tane değer ver.

array([1, 4, 9])

In [35]:
np.random.randint(20,100,10)

array([30, 96, 90, 41, 22, 76, 57, 40, 33, 33])

numpy arrays methods

In [36]:
my_numpy_list = np.arange(0,20)

In [37]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
my_numpy_list[4]

4

In [39]:
my_numpy_list[4:9] # 4'ten 9'a kadar getir.

array([4, 5, 6, 7, 8])

In [40]:
my_numpy_list[4:9:2] # 4'ten 9'a kadar ikişer ikişer git.

array([4, 6, 8])

In [41]:
my_list = list(range(0,20))

In [42]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [43]:
my_list[4:9:2]

[4, 6, 8]

In [44]:
#my_list[4:9] = -10 hata verir bu doğru bir kullanım değildir.

In [46]:
my_numpy_list[4:9] = -10 #numpy'da ise bu kullanım uygulanabilir. 4'ten 9'a kadar olan sayıları -10'a eşitle dedik.

In [47]:
my_numpy_list

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [48]:
other_list = np.arange(0,15)

In [49]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
other_list[4:10]

array([4, 5, 6, 7, 8, 9])

In [51]:
slicing_list = other_list[4:10] #yeni bir değişkene aktardık.

In [52]:
slicing_list

array([4, 5, 6, 7, 8, 9])

In [53]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
slicing_list[0]

4

In [55]:
slicing_list[:] = 100 #tüm elemanlarını 100 yapar.

In [56]:
slicing_list

array([100, 100, 100, 100, 100, 100])

In [57]:
other_list  #other_list de değişmiş numpy'da referans liste de değşir.

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14])

In [58]:
slicing_my_list = my_list[4:9]

In [59]:
slicing_my_list

[4, 5, 6, 7, 8]

In [61]:
#slicing_my_list[:] = 100 bu hata verir tümünü birden değiştiremiyoruz.

In [62]:
slicing_my_list[0] = -100 #tek tek değiştirebiliriz.

In [63]:
slicing_my_list[1] = -100

In [64]:
slicing_my_list

[-100, -100, 6, 7, 8]

In [65]:
my_list #mylist değişmedi. Liste bağımsız davranır fakat numpy'da durum böyle değildir numpy'da referans listeler alt listeler değişirse değişirler.

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [67]:
numpy_list3 = np.arange(0,20)

In [68]:
numpy_list3_copy = numpy_list3.copy()  #sağdaki diziyi alıp sol değişkene kopyalar.

In [69]:
slicing3 = numpy_list3_copy[4:9] #list3'teki elemanlardan 4 ile 9 arasındakileri aldık.

In [72]:
slicing3[:] = -100 #içindekilerin hepsini -100 yaptık.

In [73]:
slicing3

array([-100, -100, -100, -100, -100])

In [74]:
numpy_list3_copy #burası da değişti.

array([   0,    1,    2,    3, -100, -100, -100, -100, -100,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [75]:
numpy_list3 #uburası değişmedi çünkü copy kulladık. copy ile iki ayrı bellek yeri oluşturulur böylece önceden kaydettiğimiz hiçbir şey bozulmaz.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

numpy operations with numpy arrays

In [2]:
import numpy as np
new_array = np.random.randint(1,150,25) #1'den 150'ye kadar 25 tane sayı ver.

In [3]:
new_array

array([118, 131,  21,  44, 100, 127,  74,  92,  95,  81,  88, 119,  10,
       127,  18,  33, 126,  57,  66,  25,  58, 133, 129,  28,  69])

In [4]:
#dizi içinde 50'den büyük olanları görmek istiyoruz.
new_array > 50 #50'den büyük olanları true olarak döndürdü.

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False, False,  True,  True,
        True, False,  True,  True,  True, False,  True])

In [5]:
result_array = new_array > 50

In [6]:
result_array

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False, False,  True,  True,
        True, False,  True,  True,  True, False,  True])

In [7]:
new_array[result_array] # rsult arrayi  new array içine aldık. Sadece true olanları gösteriyor.

array([118, 131, 100, 127,  74,  92,  95,  81,  88, 119, 127, 126,  57,
        66,  58, 133, 129,  69])

In [8]:
last_array = np.arange(0,30) #0'dan 30'a kadar getir.

In [9]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
last_array + last_array # listeleri topluyor.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [11]:
last_array * last_array #listeleri çarpar.

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [12]:
last_array - last_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
last_array / last_array  # 0, 0'a bölünemediği için.

C:\Users\lenovo\AppData\Local\Temp\ipykernel_13628\2805399438.py:1: RuntimeWarning: invalid value encountered in divide
  last_array / last_array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [14]:
last_array.max() # en büyük değer.

29

In [15]:
np.max(last_array) #bu şekilde de en büyük bulunur.

29

In [16]:
np.mean(last_array) #sayıların ortalamasını alır.

14.5

In [17]:
np.sqrt(last_array) #sayıların karekökünü alır.

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])